local tattoos = {}

tattoos.zones = {
  { value = "head", label = "Head" },
  { value = "torso", label = "Torso" },
  { value = "left_arm", label = "Left Arm" },
  { value = "right_arm", label = "Right Arm" },
  { value = "left_leg", label = "Left Leg" },
  { value = "right_leg", label = "Right Leg" },
}

tattoos.list = {
  { collection = "mpairraces_overlays", overlay = "MP_Airraces_Tattoo_000", zone = "head", label = "Skull" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_000_F", zone = "head", label = "Biker Skull" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_000_M", zone = "head", label = "Biker Skull" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_001_F", zone = "head", label = "Biker Web" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_001_M", zone = "head", label = "Biker Web" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_M_Tat_000", zone = "head", label = "Xmas Skull" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_F_Tat_000", zone = "head", label = "Xmas Skull" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_000", zone = "head", label = "Gunrunning" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_000", zone = "head", label = "Hipster" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_000", zone = "head", label = "Hipster" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_000_F", zone = "head", label = "Stunt" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_000_M", zone = "head", label = "Stunt" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_Award_M_000", zone = "head", label = "Award" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_Award_F_000", zone = "head", label = "Award" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_000", zone = "head", label = "Skull Face" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_000", zone = "head", label = "Skull Face" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_M_Head_000", zone = "head", label = "Business" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_000_F", zone = "head", label = "Vinewood" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_000_M", zone = "head", label = "Vinewood" },

  { collection = "mpairraces_overlays", overlay = "MP_Airraces_Tattoo_001", zone = "torso", label = "Air Race Wings" },
  { collection = "mpairraces_overlays", overlay = "MP_Airraces_Tattoo_002", zone = "torso", label = "Air Race Eagle" },
  { collection = "mpairraces_overlays", overlay = "MP_Airraces_Tattoo_003", zone = "torso", label = "Air Race Skull" },
  { collection = "mpairraces_overlays", overlay = "MP_Airraces_Tattoo_004", zone = "torso", label = "Air Race Propeller" },
  { collection = "mpairraces_overlays", overlay = "MP_Airraces_Tattoo_005", zone = "torso", label = "Air Race Jet" },
  { collection = "mpairraces_overlays", overlay = "MP_Airraces_Tattoo_006", zone = "torso", label = "Air Race Dog Fight" },
  { collection = "mpairraces_overlays", overlay = "MP_Airraces_Tattoo_007", zone = "torso", label = "Air Race Vintage" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_003_F", zone = "torso", label = "Biker Flames" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_003_M", zone = "torso", label = "Biker Flames" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_004_F", zone = "torso", label = "Biker Snake" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_004_M", zone = "torso", label = "Biker Snake" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_005_F", zone = "torso", label = "Biker Eagle" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_005_M", zone = "torso", label = "Biker Eagle" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_006_F", zone = "torso", label = "Biker Cross" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_006_M", zone = "torso", label = "Biker Cross" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_M_Tat_001", zone = "torso", label = "Xmas Holly" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_F_Tat_001", zone = "torso", label = "Xmas Holly" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_M_Tat_002", zone = "torso", label = "Xmas Reindeer" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_F_Tat_002", zone = "torso", label = "Xmas Reindeer" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_M_Tat_003", zone = "torso", label = "Xmas Tree" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_F_Tat_003", zone = "torso", label = "Xmas Tree" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_001", zone = "torso", label = "Crossed Guns" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_002", zone = "torso", label = "Ammo Belt" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_003", zone = "torso", label = "War Machine" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_004", zone = "torso", label = "Battle Ready" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_001", zone = "torso", label = "Anchor" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_001", zone = "torso", label = "Anchor" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_002", zone = "torso", label = "Diamond" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_002", zone = "torso", label = "Diamond" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_003", zone = "torso", label = "Rose" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_003", zone = "torso", label = "Rose" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_001_F", zone = "torso", label = "Stunt Flames" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_001_M", zone = "torso", label = "Stunt Flames" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_002_F", zone = "torso", label = "Stunt Eagle" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_002_M", zone = "torso", label = "Stunt Eagle" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_001", zone = "torso", label = "Dragon" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_001", zone = "torso", label = "Dragon" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_002", zone = "torso", label = "Tiger" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_002", zone = "torso", label = "Tiger" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_003", zone = "torso", label = "Angel" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_003", zone = "torso", label = "Angel" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_004", zone = "torso", label = "Demon" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_004", zone = "torso", label = "Demon" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_005", zone = "torso", label = "Skull & Roses" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_005", zone = "torso", label = "Skull & Roses" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_006", zone = "torso", label = "Cross" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_006", zone = "torso", label = "Cross" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_M_Chest_000", zone = "torso", label = "Money" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_F_Chest_000", zone = "torso", label = "Money" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_M_Chest_001", zone = "torso", label = "Dollar Sign" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_F_Chest_001", zone = "torso", label = "Dollar Sign" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_001_F", zone = "torso", label = "Vinewood Star" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_001_M", zone = "torso", label = "Vinewood Star" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_002_F", zone = "torso", label = "Vinewood Camera" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_002_M", zone = "torso", label = "Vinewood Camera" },

  { collection = "mpairraces_overlays", overlay = "MP_Airraces_Tattoo_002", zone = "left_arm", label = "Air Race Wings" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_007_F", zone = "left_arm", label = "Biker Skull" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_007_M", zone = "left_arm", label = "Biker Skull" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_008_F", zone = "left_arm", label = "Chain" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_008_M", zone = "left_arm", label = "Chain" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_009_F", zone = "left_arm", label = "Mechanic" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_009_M", zone = "left_arm", label = "Mechanic" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_M_Tat_004", zone = "left_arm", label = "Xmas Candy" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_F_Tat_004", zone = "left_arm", label = "Xmas Candy" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_005", zone = "left_arm", label = "Pistol" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_006", zone = "left_arm", label = "Grenade" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_004", zone = "left_arm", label = "Camera" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_004", zone = "left_arm", label = "Camera" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_005", zone = "left_arm", label = "Compass" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_005", zone = "left_arm", label = "Compass" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_003_F", zone = "left_arm", label = "Racing" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_003_M", zone = "left_arm", label = "Racing" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_007", zone = "left_arm", label = "Tribal" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_007", zone = "left_arm", label = "Tribal" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_008", zone = "left_arm", label = "Sleeve" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_008", zone = "left_arm", label = "Sleeve" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_009", zone = "left_arm", label = "Snake" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_009", zone = "left_arm", label = "Snake" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_M_LeftArm_000", zone = "left_arm", label = "Business Clock" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_F_LeftArm_000", zone = "left_arm", label = "Business Clock" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_M_LeftArm_001", zone = "left_arm", label = "Business Suit" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_F_LeftArm_001", zone = "left_arm", label = "Business Suit" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_003_F", zone = "left_arm", label = "Film Strip" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_003_M", zone = "left_arm", label = "Film Strip" },

  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_010_F", zone = "right_arm", label = "Biker Wings" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_010_M", zone = "right_arm", label = "Biker Wings" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_011_F", zone = "right_arm", label = "Piston" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_011_M", zone = "right_arm", label = "Piston" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_012_F", zone = "right_arm", label = "Wrench" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_012_M", zone = "right_arm", label = "Wrench" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_M_Tat_005", zone = "right_arm", label = "Xmas Stocking" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_F_Tat_005", zone = "right_arm", label = "Xmas Stocking" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_007", zone = "right_arm", label = "Rifle" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_008", zone = "right_arm", label = "Bullet" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_006", zone = "right_arm", label = "Feather" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_006", zone = "right_arm", label = "Feather" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_007", zone = "right_arm", label = "Arrow" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_007", zone = "right_arm", label = "Arrow" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_004_F", zone = "right_arm", label = "Nitro" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_004_M", zone = "right_arm", label = "Nitro" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_010", zone = "right_arm", label = "Rose" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_010", zone = "right_arm", label = "Rose" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_011", zone = "right_arm", label = "Dagger" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_011", zone = "right_arm", label = "Dagger" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_012", zone = "right_arm", label = "Barbed Wire" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_012", zone = "right_arm", label = "Barbed Wire" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_M_RightArm_000", zone = "right_arm", label = "Business Card" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_F_RightArm_000", zone = "right_arm", label = "Business Card" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_M_RightArm_001", zone = "right_arm", label = "Gold Watch" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_F_RightArm_001", zone = "right_arm", label = "Gold Watch" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_004_F", zone = "right_arm", label = "Spotlight" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_004_M", zone = "right_arm", label = "Spotlight" },

  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_013_F", zone = "left_leg", label = "Biker Boot" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_013_M", zone = "left_leg", label = "Biker Boot" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_014_F", zone = "left_leg", label = "Gear Shift" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_014_M", zone = "left_leg", label = "Gear Shift" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_M_Tat_006", zone = "left_leg", label = "Xmas Snowflake" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_F_Tat_006", zone = "left_leg", label = "Xmas Snowflake" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_009", zone = "left_leg", label = "Dog Tag" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_008", zone = "left_leg", label = "Bicycle" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_008", zone = "left_leg", label = "Bicycle" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_005_F", zone = "left_leg", label = "Checkered" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_005_M", zone = "left_leg", label = "Checkered" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_013", zone = "left_leg", label = "Star" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_013", zone = "left_leg", label = "Star" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_014", zone = "left_leg", label = "Flame" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_014", zone = "left_leg", label = "Flame" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_M_LeftLeg_000", zone = "left_leg", label = "Business Chain" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_F_LeftLeg_000", zone = "left_leg", label = "Business Chain" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_005_F", zone = "left_leg", label = "Director" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_005_M", zone = "left_leg", label = "Director" },

  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_015_F", zone = "right_leg", label = "Biker Chain" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_015_M", zone = "right_leg", label = "Biker Chain" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_016_F", zone = "right_leg", label = "Road" },
  { collection = "mpbiker_overlays", overlay = "MP_MP_Biker_Tat_016_M", zone = "right_leg", label = "Road" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_M_Tat_007", zone = "right_leg", label = "Xmas Bell" },
  { collection = "mpchristmas2_overlays", overlay = "MP_Xmas2_F_Tat_007", zone = "right_leg", label = "Xmas Bell" },
  { collection = "mpgunrunning_overlays", overlay = "MP_Gunrunning_Tattoo_010", zone = "right_leg", label = "Knife" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_M_Tat_009", zone = "right_leg", label = "Record" },
  { collection = "mphipster_overlays", overlay = "FM_Hip_F_Tat_009", zone = "right_leg", label = "Record" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_006_F", zone = "right_leg", label = "Turbo" },
  { collection = "mpstunt_overlays", overlay = "MP_MP_Stunt_Tat_006_M", zone = "right_leg", label = "Turbo" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_015", zone = "right_leg", label = "Spider" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_015", zone = "right_leg", label = "Spider" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_M_016", zone = "right_leg", label = "Scorpion" },
  { collection = "multiplayer_overlays", overlay = "FM_Tat_F_016", zone = "right_leg", label = "Scorpion" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_M_RightLeg_000", zone = "right_leg", label = "Business Cigar" },
  { collection = "mpbusiness_overlays", overlay = "MP_Buis_F_RightLeg_000", zone = "right_leg", label = "Business Cigar" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_006_F", zone = "right_leg", label = "Red Carpet" },
  { collection = "mpvinewood_overlays", overlay = "MP_Vinewood_Tat_006_M", zone = "right_leg", label = "Red Carpet" },
}

return tattoos
